SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(BS.SALES * M.PRICE) AS TOTAL_SALES
FROM (SELECT B.BOOK_ID, B.CATEGORY, B.PRICE, A.AUTHOR_ID, A.AUTHOR_NAME
      FROM BOOK B 
      JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID) M 
JOIN BOOK_SALES BS ON M.BOOK_ID = BS.BOOK_ID
WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '01'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;

