-- MAX()를 사용해 가장 큰 조회수 값 찾기
SELECT CONCAT('/home/grep/src/', F.BOARD_ID, "/",F.FILE_ID,F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD B
         JOIN USED_GOODS_FILE F
              ON B.BOARD_ID = F.BOARD_ID
WHERE VIEWS = (SELECT MAX(VIEWS)
               FROM USED_GOODS_BOARD)

ORDER BY F.FILE_ID DESC