-- 풀이1. IN 사용
SELECT NAME
FROM ANIMAL_INS
WHERE DATETIME IN (SELECT MIN(DATETIME) FROM ANIMAL_INS)

-- 풀이2. = 사용
SELECT NAME
FROM ANIMAL_INS
WHERE DATETIME = (SELECT MIN(DATETIME) FROM ANIMAL_INS)

-- 풀이3. LIMIT 사용
SELECT NAME
FROM ANIMAL_INS
ORDER BY DATETIME
    LIMIT 1