SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID,
       R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD B JOIN USED_GOODS_REPLY R USING (BOARD_ID)
WHERE B.CREATED_DATE LIKE '2022-10%'
ORDER BY R.CREATED_DATE, B.TITLE;

-- WHERE B.CREATED_DATE LIKE '2022-10%' 대신
-- WHERE DATE_FORMAT(B.CREATED_DATE, '%Y-%m') = '2022-10'나
-- WHERE SUBSTR(B.CREATED_DATE,1,7) = '2022-10' 도 가능
